Dodano animacje na hover w settings i do kazdego hovera w elemencie
matwjablonski/kodilla-wdp-2204-03 pull request #10
Opened 2022-04-16 18:21 UTC by SerhiiSSS

2022-04-19 13:34 UTC, matwjablonski requested changes
1) brak opisu zadania

2) rozwiąż konflikty

2022-04-19 13:34 UTC, matwjablonski commented on src/styles/settings.scss
> +  border-color 0.25s,
daj jakieś wcięcie dla następnych animacji, bo jest nieczytelnie, ewentualnie zamień wszystko na `all 0.25s`

2022-04-19 14:21 UTC, SerhiiSSS commented on src/styles/settings.scss
> +  border-color 0.25s,
nie do końca zrozumiałem o co Ci chodzi ale jak tak poprawie bedzie ok?

%hover-params {
  transition: background-color,
  border-color ,
  color,
  transform ,
  opacity ,

  all 0.50s;
}

2022-04-25 14:47 UTC, pantera272 approved these changes

2022-04-26 21:02 UTC, spawlaczyk approved these changes

2022-04-27 07:02 UTC, merged