Task wdp220403 12
matwjablonski/kodilla-wdp-2204-03 pull request #16
Opened 2022-04-18 21:35 UTC by SerhiiSSS

Dodano nowy component (CompareBox), porównania productu

2022-04-19 13:43 UTC, matwjablonski requested changes

2022-04-19 13:43 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +
ta linia przerwy jest zbędna

2022-04-20 11:48 UTC, spawlaczyk requested changes
Checki skończyły się niepowodzeniem, chyba trzeba zrobić pulla z mastera na ten branch.

2022-04-20 11:59 UTC, matwjablonski requested changes

2022-04-20 11:59 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +  .outlines .selected{
spacja przed {

2022-04-20 11:59 UTC, matwjablonski commented on src/components/features/CompareBox/CompareBox.js
> +  } else {
else zbędny, wystarczy return

2022-04-20 11:59 UTC, matwjablonski commented on src/components/features/CompareBox/CompareBox.module.scss
> +
dodatkowa pusta linia zbędna

2022-04-20 11:59 UTC, matwjablonski commented on src/components/features/CompareBox/CompareBox.module.scss
> +    border: 10px solid #fff;
kolor ze zmiennych

2022-04-20 11:59 UTC, matwjablonski commented on src/components/features/CompareBox/CompareBox.module.scss
> +  background: rgba(213, 142, 50, 0.7);
kolor ze zmiennych

2022-04-20 11:59 UTC, matwjablonski commented on src/components/features/CompareBox/CompareBox.module.scss
> +        opacity: 6;
6? opacity może przyjąć zakres od 0 do 1 lub w %

2022-04-20 11:59 UTC, matwjablonski commented on src/components/features/CompareBox/CompareBox.module.scss
> +      color: #fff;
kolory ze zmiennych

2022-04-20 11:59 UTC, matwjablonski commented on src/components/features/CompareBox/CompareBox.module.scss
> +
zbędna pusta linia

2022-04-20 11:59 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
zbędna pusta linia

2022-04-20 11:59 UTC, matwjablonski commented on src/redux/productsRedux.js
> +// action name creator
po co te komentarze - z samych nazw widać co to jest ;)

2022-04-20 11:59 UTC, matwjablonski commented on src/redux/productsRedux.js
> +        if (product.compare === true) {
```if (product.compare)```

2022-04-20 12:06 UTC, SerhiiSSS commented on src/redux/productsRedux.js
> +// action name creator
pisałem dla lepszej czytelności ,tak samo po to i puste linii dodaje
jak to nie potrzebne to poprawie jutro

2022-04-20 12:07 UTC, matwjablonski commented on src/redux/productsRedux.js
> +// action name creator
- komentarze spoko o ile z nazwy nie da się wywnioskować do czego służą dane zmienne
- puste linie spoko o ile rozdzielają logiczne części kodu

2022-04-20 13:46 UTC, spawlaczyk commented on src/components/common/ProductBox/ProductBox.module.scss
> +    color: white;
color i border-color mogłyby mieć kolor ze zmiennych

2022-04-20 13:46 UTC, spawlaczyk commented on src/components/common/ProductBox/ProductBox.module.scss
> +  .outlines .state:hover{
tu też można dać spację przed {

2022-04-20 13:49 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.module.scss
> +    color: white;
zdecydowanie, używanie kolorów nazwanych jest złą praktyką

2022-04-21 13:31 UTC, RobertGraupner approved these changes

2022-04-21 17:59 UTC, matwjablonski commented
konflikty

2022-04-23 08:13 UTC, matwjablonski requested changes

2022-04-23 08:13 UTC, matwjablonski commented on src/components/common/ProductBox/ProductBox.js
> +const ProductBox = ({ name, price, promo, stars, compare, handleCompareClick, id, isFavorite}) => (
Za długa linia, zmień proszę formatowanie

2022-04-23 08:13 UTC, matwjablonski commented on src/components/features/CompareBox/CompareBox.js
> +  return '';
return null

2022-04-26 21:11 UTC, spawlaczyk reviewed
Są konflikty do rozwiązania, kliknięcie add to compare mogłoby mieć zablokowane zachowanie domyślne a box z porównywanymi produktami mógłby się przyklejać do dołu viewportu (chyba można to osiągnąć przez position sticky)

2022-05-04 10:19 UTC, pantera272 commented
konflikty

2022-05-05 08:19 UTC, merged