Pepair cart shopping view
matwjablonski/kodilla-wdp-2204-03 pull request #21
Opened 2022-04-20 08:16 UTC by pantera272

Problem: Liczba przy koszyku przy większych ilościach, zasłaniała ikonę koszyka i źle to wyglądało.
Rozwiązanie: Otoczenie liczby kolejnym div-em i ostylowanie go poprzez dodanie lewego marginesu i i wyrównania tekstu do lewej

2022-04-20 08:27 UTC, matwjablonski approved these changes

2022-04-20 09:46 UTC, RobertGraupner approved these changes

2022-04-20 09:52 UTC, matwjablonski requested changes
na urządzeniu mobilnym liczba wychodzi poza ekran, wpisałem 999 i już się nie zmieściło.

2022-04-20 11:51 UTC, matwjablonski requested changes

2022-04-20 11:51 UTC, matwjablonski commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +    margin-right: 40px;
to nie jest najlepszy sposób - wpisanie na sztywno tej wartości spowoduje że sztucznie odsuniesz element od krawędzi

wydaje mi się, że powinieneś zrobić to w taki sposób, że element koszyka był przyczepiony do prawej strony ale miał zmienną szerokość

w tym momencie cartCounter ma na sztywno szerokość 28px, gdyby szerokość była dynamiczna to ten problem by się nie pojawiał, natomiast jeśli width będzie auto pojawi się nowy problem do rozwiązania ;)

2022-04-21 12:38 UTC, SerhiiSSS commented
masz  konflikt do rozwiązania

2022-04-21 12:55 UTC, SerhiiSSS commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +      .cartCounterText{
spacja przed {

2022-04-21 20:18 UTC, spawlaczyk requested changes

2022-04-21 20:18 UTC, spawlaczyk commented on src/components/layout/CompanyClaim/CompanyClaim.module.scss
> +        color: rgb(224, 227, 237);
Możesz dać kolor ze zmiennych

2022-04-22 09:11 UTC, closed without merging