Add RWD for NewFurniture
matwjablonski/kodilla-wdp-2204-03 pull request #25
Opened 2022-04-21 12:28 UTC by SerhiiSSS

dodano RWD dla wersji mob i do tabletów

2022-04-21 15:07 UTC, RobertGraupner submitted a review, later dismissed

2022-04-21 17:45 UTC, matwjablonski commented
https://jmp.sh/iWZC0oC


ogólnie wygląda słabo to RWD dla tej sekcji - brakuje przerw, łamie się w losowym momencie

2022-04-21 17:45 UTC, matwjablonski requested changes
RWD do poprawy

2022-04-22 11:57 UTC, spawlaczyk reviewed
Na tabletach wg mnie wygląda spoko ale poprawiłbym listę kategorii (może bardziej na środek i żeby się nie przechodziła linię niżej)
https://imgur.com/a/S2pPWME

2022-04-22 19:57 UTC, pantera272 commented on src/components/features/NewFurniture/NewFurniture.module.scss
>          li {
Dodawałbym między klasami pustą linię odstępu, w niektórych ją masz a w niektórych nie.

2022-04-22 20:10 UTC, pantera272 commented
Może warto by było przyciski "Quick view" i "Add to cart" ustawić pod sobą a nie obok siebie. Wyrównałbym też te linie przy linkach mają różne długości. Jeszcze powstanie bug przez przyciski favorite, porównaniem i ceną ja miałem zadanie gdzie przed obecną ceną jest stara tu się na mobile się pewno nie zmieści.

2022-04-23 09:31 UTC, matwjablonski commented
![image](https://user-images.githubusercontent.com/20933197/164888868-806592ac-1a52-4bf1-8282-f471bb34f30f.png)

To wyglada kiepsko, to powinna być jakaś lista /select/ na mobilce.

2022-05-03 20:17 UTC, pantera272 approved these changes

2022-05-04 07:26 UTC, merged