Add setting current RWD mode
matwjablonski/kodilla-wdp-2204-03 pull request #26
Opened 2022-04-21 17:15 UTC by spawlaczyk

Problem: 
Na podstawie zmiany szerokości viewportu ma być ustalany tryb RWD (desktop, tablet, mobile)
Rozwiązanie:
Dodałem do stanu właściwości: viewportWidth (ustalane przez window.innerWidth), desktop, tablet oraz mobile (wszystkie domyślnie przyjmują wartość false). W momencie podłączenia komponentu (dzięki funkcji componentDidMount) wywołuję funkcję odpowiedzialną za przypisanie akutalnej szerokości viewportu (updateViewportWidth), na componentDidMount jest też nałożony eventListener oczekujący na zdarzenie 'resize' i włączający w odpowiedzi funckję updateViewportWidth. Tamta funkcja uruchamia handleUpdateWidth który warunkowo zmienia wartość odpowiedniej właściwości (desktop, tablet lub mobile) z false na true. W render stworzyłem tablicę classes, do której dodaję odpowiednią klasę 'col-' w zależności od tego, która właściwość ma wartość true. Klasa jest nadawana na diva rodzica przechowującego <ProductBox>.

2022-04-21 17:52 UTC, matwjablonski requested changes

2022-04-21 17:52 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +  updateViewportWidth = () => {
metody w klasie nie powinny być arrow function

2022-04-21 17:52 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +    if (this.state.viewportWidth >= 922) {
stosowanie liczb w taki sposób to antywzorzec - MagicNumbers 

powinieneś przypisać je do zmiennych i następnie wykorzystać

np. 
```js
const MEDIUM_BREAKPOINT_SIZE = 992;
```

2022-04-21 17:52 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +    if (desktop) {
wynieś logikę przydzielania klasy do osobnej funkcji

2022-04-21 17:52 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
>              {categoryProducts.slice(activePage * 8, (activePage + 1) * 8).map(item => (
co to za działania matematyczne - MagicNumbers

2022-04-21 20:03 UTC, spawlaczyk commented on src/components/features/NewFurniture/NewFurniture.js
>              {categoryProducts.slice(activePage * 8, (activePage + 1) * 8).map(item => (
Tego fragmentu na razie nie ruszałem bo przeczytałem w innym zadaniu (tym dot. RWD dla newFurniture), że później będzie inne zadanie dot. tego ile produktów jest wyświetlane.

2022-04-27 07:06 UTC, matwjablonski requested changes

2022-04-27 07:06 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +                  desktop ? 'col-3' : tablet ? 'col-6' : mobile ? 'col-12' : ''
napisz proszę zwykłą funkcję do tego - taki zapis jest nieczytelny - nie zagnieżdżajmy wielokrotnie ternary operators

2022-04-28 14:16 UTC, spawlaczyk commented on src/components/features/NewFurniture/NewFurniture.js
> +                  desktop ? 'col-3' : tablet ? 'col-6' : mobile ? 'col-12' : ''
A czy do nadawania klasy konieczna jest osobna funckja? Bo w sumie jak teraz do tego siadłem to wpadł mi do głowy pomysł żeby dodać do stanu activeClass (domyślnie pusty string) i w ciele metody handleUpdateWidth (ze zmienioną nazwą np. na setCurrentMode) zmieniać wartość activeClass w tym samym momencie, w którym zmieniam wartość desktop, tablet i mobile. Cały kod odpowiedzialny za zmianę trybu byłby w jednej metodzie ale wolę dopytać bo nie wiem jak to się będzie miało do dobrych praktyk i ogólnej czytelności.

2022-04-30 15:57 UTC, SerhiiSSS approved these changes

2022-05-01 17:11 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +                  desktop ? 'col-3' : tablet ? 'col-6' : mobile ? 'col-12' : ''
Nie jest potrzebna, po prostu zagnieżdżanie ternary nie jest czytelne i powinno się tego unikać

2022-05-01 17:12 UTC, matwjablonski approved these changes

2022-05-01 17:15 UTC, merged