Fix styling select/WDP220403-7
matwjablonski/kodilla-wdp-2204-03 pull request #3
Opened 2022-04-15 19:37 UTC by SerhiiSSS

2022-04-19 10:56 UTC, spawlaczyk submitted a review, later dismissed

2022-04-19 10:58 UTC, matwjablonski requested changes
PR nie ma opisu - proszę dodaj

2022-04-19 10:58 UTC, matwjablonski commented on src/components/common/FeatureBox/FeatureBox.module.scss
> +
po co dodałeś tę linię?

2022-04-19 10:58 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      font-size: small;
dlaczego `small`? zasadniczo absolutne deklarowanie wartości font-size może być troszkę mylące. `small` jest zależy od domyślnej wartości dla `medium` - pytanie jakie jest medium w tym projekcie?

2022-04-19 11:31 UTC, SerhiiSSS commented on src/components/common/FeatureBox/FeatureBox.module.scss
> +
przypadkowo, juz poprawiłem

2022-04-19 11:31 UTC, SerhiiSSS commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      font-size: small;
Już poprawiłem. Proszę sprawdzić

2022-04-19 11:33 UTC, matwjablonski requested changes

2022-04-19 11:33 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +              <div key={item.id} className='col-3 '>
po co te spacje na końcu?

2022-04-19 11:33 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +          <div className='row '>
po co te spacje na końcu?

2022-04-19 11:35 UTC, matwjablonski reviewed
dodatkowo masz konflikty proszę - dociągnij mastera i rozwiąż konflikty

2022-04-19 11:37 UTC, SerhiiSSS commented on src/components/features/NewFurniture/NewFurniture.js
> +          <div className='row '>
spacje na końcu bo rozpoczął zadanie [WDP220403-17] i w trakcie pracy przełączyłem na branch [WDP220403-7] a zmiany nie były zapisane

2022-04-19 11:38 UTC, matwjablonski commented on src/components/features/NewFurniture/NewFurniture.js
> +          <div className='row '>
popraw proszę - w PR tylko to co potrzebne

2022-04-20 10:37 UTC, matwjablonski commented
konflikty, zobacz do zakładki Files changed czy na pewno masz wszystko

2022-04-20 18:27 UTC, RobertGraupner approved these changes

2022-04-20 19:15 UTC, matwjablonski approved these changes

2022-04-20 19:15 UTC, merged