Add RWD for footer
matwjablonski/kodilla-wdp-2204-03 pull request #32
Opened 2022-04-23 14:41 UTC by pantera272

Problem: Brak RWD dla stopki, wymagania na małych urządzeniach po 2 kolumny, na większych 4. Copyright na małych urządzeniach do prawej, Socjalki do lewej.

Rozwiązanie: Ostylowanie pod wymagania klienta, zmieniłem także sposób wyświetlania płatności, gdyż na tabletach jego część była niewidoczna.

Ps. Osobiście ustawiłbym socjalki nad copyright, lepiej by to wyglądało na mobile.

2022-04-23 21:05 UTC, spawlaczyk requested changes
Socjalki łamią się w losowym momencie to można zmienić, poza tym moim zdaniem wszystko ok

2022-04-27 11:53 UTC, RobertGraupner approved these changes

2022-04-28 10:16 UTC, matwjablonski approved these changes

2022-04-28 12:01 UTC, spawlaczyk approved these changes

2022-04-28 13:12 UTC, merged