Task wdp220403 21
matwjablonski/kodilla-wdp-2204-03 pull request #33
Opened 2022-04-24 16:38 UTC by pantera272

Problem: Dodanie obsługi gwiazdek w ProductBox, na czarno mają się wyświetlać gwiazdki które nie były ocenione przez użytkownika, na pomarańczowo ocenione przez użytkownika.

Rozwiązanie: Dodanie nowego komponentu StarRating, odpowiedzialnego za obsługę gwiazdek, dodanie nowej wartości do stanu produktu userRatnig, false - nie ocenione przez użytkownika, true - ocenione

2022-04-26 13:56 UTC, SerhiiSSS approved these changes

2022-04-26 21:12 UTC, spawlaczyk approved these changes

2022-04-27 07:14 UTC, matwjablonski requested changes

2022-04-27 07:14 UTC, matwjablonski commented on src/components/features/StarRating/StarRating.js
> +          id={id}
każdy button ma to samo id, id powinno być unikalne

jeśli wykorzystujesz to gdzieś indziej to wykorzystaj inny atrybut np. name

2022-05-03 14:16 UTC, SerhiiSSS approved these changes

2022-05-03 14:46 UTC, merged