Wdp220403 22
matwjablonski/kodilla-wdp-2204-03 pull request #35
Opened 2022-04-26 13:22 UTC by SerhiiSSS

Dodano sekcje  "Promotion" według designu 
https://uploads.kodilla.com/bootcamp/wdp/group-project-01/section-featured.png

2022-04-26 21:20 UTC, spawlaczyk approved these changes

2022-04-27 11:34 UTC, RobertGraupner submitted a review, later dismissed

2022-05-02 16:45 UTC, spawlaczyk requested changes
wszystko ok tylko konflikty do rozwiązania

2022-05-03 13:40 UTC, spawlaczyk approved these changes

2022-05-03 20:12 UTC, pantera272 commented
Hej. Trzy linijki kodu.
border - przy buttonach (prawo, lewo) chyba lepiej żeby go nie było jak na designie, chyba ze mi się wydaje
trzy kropki slidera - dałbym cursor: pointer to jednak wygląd
no i shop now troche niżej, ale dla mnie to by już problemu nie stanowiło

2022-05-05 08:34 UTC, SerhiiSSS commented
> Хей. Trzy linijki kodu. border - przy buttonach (prawo, lewo) chyba lepiej żeby go nie było jak na designie, chyba ze mi się wydaje trzy kropki slidera - dałbym курсор: покажчик на jednak wygląd no i shop now troche niżej, ale dla mnie problem to nieju stanowiło

2022-05-05 08:38 UTC, SerhiiSSS commented
> Хей Trzy linijki kodu. border - przy buttonach (prawo, lewo) chyba lepiej żeby go nie było jak na designie, chyba ze mi się wydaje trzy kropki slidera - dałbym курсор: покажчик на рівний wygląd no i shop now troche niżej, ale dla mnie mnie problem to niło

Dałem cursor do slidera i troche opuściłem shop now, buttony mom zdaniem jest ok, ale jak coś to póżniej pobawię się z tym, narazię nie tak dużo czasu mam

2022-05-05 08:39 UTC, merged