Dodano rozwijany wybór kategorii w search
matwjablonski/kodilla-wdp-2204-03 pull request #8
Opened 2022-04-16 15:37 UTC by SerhiiSSS

2022-04-19 12:10 UTC, matwjablonski requested changes
brak opisu

2022-04-19 12:10 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.js
> +              <li>Bad</li>
nie lepiej zrobić to dynamicznie - przygotować tablicę z opcjami i przemapować się po nich?

2022-04-19 12:10 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      color: #ffff;
kolor ze zmiennych poproszę

2022-04-19 12:10 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +        border: solid 1px #292929;
jak wyżej - kolory poproszę ze zmiennych

2022-04-19 12:40 UTC, SerhiiSSS commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      color: #ffff;
nie dodałem zmiennych bo nie było zrobionego [merge] myśliałem potem poprawić jak bedzie dodany zmienny styl w settings zeby nie było konfliktu

2022-04-19 12:41 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.module.scss
> +      color: #ffff;
poczekajmy zatem na merge ;) i od razu poprawimy w tym PRze

2022-04-21 18:01 UTC, matwjablonski requested changes

2022-04-21 18:01 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.js
> +                  <li key={selects.toString()}>{select}</li>
klucz nie będzie unikalny - skoro całą tablicę za każdym razem do stringa sprowadzasz  - wszystkie li będą miały ten sam klucz

2022-04-21 18:02 UTC, matwjablonski commented
https://jmp.sh/ScDv8u6

mogłoby to być wyrównane

2022-04-23 08:15 UTC, matwjablonski commented
Nie wszystkie komentarze rozwiązane

2022-04-26 21:01 UTC, spawlaczyk submitted a review, later dismissed

2022-04-30 12:00 UTC, SerhiiSSS commented
> Nie wszystkie komentarze rozwiązane

jeszcze raz przepatrzyłem kod chyba wszystkie komentarze były poprawione
prosze ukazać na komentarz który przegapiłem

2022-05-01 17:08 UTC, matwjablonski requested changes

2022-05-01 17:08 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.js
> +              <ul key={selects.id}>
Ten key jest zbędny, key dajemy dla elementów listy

2022-05-01 17:08 UTC, matwjablonski commented on src/components/features/ProductSearch/ProductSearch.js
> +              <ul key={selects.id}>
Poza tym id nie występuje w obiekcie selects

2022-05-03 13:39 UTC, spawlaczyk submitted a review, later dismissed

2022-05-04 10:21 UTC, pantera272 commented
dalej konflikt

2022-05-05 08:18 UTC, merged